"""
app.py – Interactive CLI for image classification with the trained ResNet-18.

Usage:
    python app.py

Requires:
    resnet_model.pth  (generated by main.py or the notebook)
"""

import sys
import torch
from pathlib import Path

from classes import ResNet18, preprocess_image, CIFAR10_CLASSES

MODEL_PATH = 'resnet_model.pth'


def load_model(path: str) -> ResNet18:
    checkpoint = torch.load(path, map_location='cpu', weights_only=False)
    model      = ResNet18(num_classes=10)
    model.load_state_dict(checkpoint['model_state'])
    model.eval()
    return model


def predict(model: ResNet18, image_path: str) -> tuple[str, float, list[tuple[str, float]]]:
    """
    Returns (predicted_class, confidence_pct, top5_list).
    top5_list is [(class_name, prob_pct), ...] sorted descending.
    """
    tensor = preprocess_image(image_path)

    with torch.no_grad():
        logits = model(tensor)                          # (1, 10)
        probs  = torch.softmax(logits, dim=1)[0]        # (10,)

    top5_idx  = probs.argsort(descending=True)[:5]
    top5      = [(CIFAR10_CLASSES[i], probs[i].item() * 100) for i in top5_idx]

    pred_idx  = top5_idx[0].item()
    return CIFAR10_CLASSES[pred_idx], probs[pred_idx].item() * 100, top5


def main():
    print("=" * 50)
    print("  ResNet-18 – CIFAR-10 Image Classifier")
    print("=" * 50)

    if not Path(MODEL_PATH).exists():
        print(f"ERROR: model file '{MODEL_PATH}' not found.")
        print("Run main.py or the notebook first to train and save the model.")
        sys.exit(1)

    print(f"\nLoading model from {MODEL_PATH} …")
    model = load_model(MODEL_PATH)
    print("Model ready.\n")

    print("CIFAR-10 classes:", ', '.join(CIFAR10_CLASSES))

    while True:
        path = input("\nEnter image path (or 'q' to quit): ").strip()
        if path.lower() in ('q', 'quit', 'exit'):
            break

        if not Path(path).exists():
            print(f"  File not found: {path}")
            continue

        try:
            label, conf, top5 = predict(model, path)
        except Exception as e:
            print(f"  Error processing image: {e}")
            continue

        print("\n" + "=" * 50)
        print(f"  Prediction : {label.upper()}")
        print(f"  Confidence : {conf:.1f}%")
        print("\n  Top-5 predictions:")
        for rank, (cls, prob) in enumerate(top5, 1):
            bar = '#' * int(prob / 5)
            print(f"    {rank}. {cls:<12s}  {prob:5.1f}%  {bar}")
        print("=" * 50)

    print("Goodbye!")


if __name__ == '__main__':
    main()
