"""
app.py – Interactive CLI application for Heart Disease prediction.

Usage:
    python app.py

Requires:
    heart_model.pth  (generated by main.py)
"""

import torch
import numpy as np
from classes import HeartDiseaseModel

MODEL_PATH = 'heart_model.pth'


def ask_int(prompt: str, valid: list[int] | None = None) -> int:
    while True:
        try:
            val = int(input(prompt).strip())
            if valid is not None and val not in valid:
                print(f"  Please enter one of: {valid}")
                continue
            return val
        except ValueError:
            print("  Invalid input. Please enter an integer.")


def ask_float(prompt: str, min_val: float = 0.0, max_val: float = 1e9) -> float:
    while True:
        try:
            val = float(input(prompt).strip())
            if not (min_val <= val <= max_val):
                print(f"  Please enter a value between {min_val} and {max_val}.")
                continue
            return val
        except ValueError:
            print("  Invalid input. Please enter a number.")


def collect_features() -> list[float]:
    print("\n" + "=" * 50)
    print("  Heart Disease Risk Predictor")
    print("=" * 50)
    print("Please answer the following questions:\n")

    age      = ask_float("Age (years): ", 1, 120)
    sex      = ask_int("Sex (1 = Male, 0 = Female): ", valid=[0, 1])
    cp       = ask_int(
        "Chest pain type\n"
        "  0 = Typical angina\n"
        "  1 = Atypical angina\n"
        "  2 = Non-anginal pain\n"
        "  3 = Asymptomatic\n"
        "Your choice: ", valid=[0, 1, 2, 3])
    trestbps = ask_float("Resting blood pressure (mm Hg): ", 50, 250)
    chol     = ask_float("Serum cholesterol (mg/dl): ", 50, 700)
    fbs      = ask_int("Fasting blood sugar > 120 mg/dl? (1 = Yes, 0 = No): ", valid=[0, 1])
    restecg  = ask_int(
        "Resting ECG results\n"
        "  0 = Normal\n"
        "  1 = ST-T wave abnormality\n"
        "  2 = Left ventricular hypertrophy\n"
        "Your choice: ", valid=[0, 1, 2])
    thalach  = ask_float("Maximum heart rate achieved: ", 50, 250)
    exang    = ask_int("Exercise-induced angina? (1 = Yes, 0 = No): ", valid=[0, 1])
    oldpeak  = ask_float("ST depression induced by exercise relative to rest: ", 0.0, 10.0)
    slope    = ask_int(
        "Slope of peak exercise ST segment\n"
        "  0 = Upsloping\n"
        "  1 = Flat\n"
        "  2 = Downsloping\n"
        "Your choice: ", valid=[0, 1, 2])
    ca       = ask_int("Number of major vessels colored by fluoroscopy (0–3): ", valid=[0, 1, 2, 3])
    thal     = ask_int(
        "Thalassemia\n"
        "  0 = Normal\n"
        "  1 = Fixed defect\n"
        "  2 = Reversible defect\n"
        "Your choice: ", valid=[0, 1, 2])

    return [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal]


def predict(features: list[float], model: HeartDiseaseModel, scaler) -> tuple[int, float]:
    X_raw = np.array(features, dtype='float32').reshape(1, -1)
    X_scaled = scaler.transform(X_raw)
    X_tensor = torch.tensor(X_scaled, dtype=torch.float32)

    model.eval()
    with torch.no_grad():
        logits = model(X_tensor)
        probs  = torch.softmax(logits, dim=1)
        pred   = probs.argmax(1).item()
        confidence = probs[0, pred].item()

    return pred, confidence


def main():
    # Load model and scaler
    checkpoint = torch.load(MODEL_PATH, map_location='cpu', weights_only=False)
    scaler = checkpoint['scaler']

    model = HeartDiseaseModel()
    model.load_state_dict(checkpoint['model_state'])

    while True:
        features = collect_features()
        pred, conf = predict(features, model, scaler)

        print("\n" + "=" * 50)
        if pred == 1:
            print(f"  RESULT: Heart disease DETECTED")
        else:
            print(f"  RESULT: No heart disease detected")
        print(f"  Confidence: {conf * 100:.1f}%")
        print("=" * 50)
        print("\nDISCLAIMER: This is a machine-learning demo, not medical advice.")

        again = input("\nPredict again? (y/n): ").strip().lower()
        if again != 'y':
            break

    print("Goodbye!")


if __name__ == '__main__':
    main()
